[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  python_version = "3.9"

[dev]
  functions = "netlify/functions"
  publish = "."