services:
  - type: web
    name: great-british-bike-off
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false